특수문자 query 생성 시 처리하기
Foundy-LLC/p_lyric pull request #72
Opened 2021-11-27 09:28 UTC by alpha-src

## Uri.encodeFull() 함수에서의 미비점 발견

![image](https://user-images.githubusercontent.com/54366260/143675778-1b58a25c-4879-410d-aa4b-fc3cd3b87bf2.png)

위 사진을 보면 Uri.encodeFull 메소드는 특수문자들은 encode가 되지 않는다고 설명되있음.
그렇기에 특수문자가 포함된 제목들을 검색할 때 예상치 못한 노래 결과들이 나오는 현상이 발견됐지만
`encodeSpecial` 함수가 처리해줄 것임

2021-11-28 04:35 UTC, jja08111 requested changes

2021-11-28 04:35 UTC, jja08111 commented on lib/services/bugs_lyrics_scraper.dart
> +  print(searchPageUrl);
로그를 디테일하게 나타내는게 나을듯 
예를 들어 검색한 페이지 URL: ~~~

아니면 아예 이 문장을 삭제하거나

2021-11-28 04:35 UTC, jja08111 commented on lib/models/song.dart
> +    //required this.coverImage,
주석 삭제 부탁

2021-11-28 04:35 UTC, jja08111 commented on lib/models/song.dart
> +    this.lyrics = "곡 정보가 없습니다 😢";
초기에는 ""으로 비워두고 나중에 찾았을때 없는 경우 이 문장을 넣는게 나아보여
19라인도 마찬가지로

2021-11-28 04:35 UTC, jja08111 commented on lib/services/bugs_lyrics_scraper.dart
> +      throw NO_RESULT;
에러를 던지려면 차라리 Exception 클래스를 상속해서 하는게 나아보임

이름은 NoResultException 등등 처럼

2021-11-28 04:35 UTC, jja08111 commented on lib/services/bugs_lyrics_scraper.dart
> +  searchQuery = encodeSpecial(searchQuery);
여기 한문장으로 처리해도 댈듯
```suggestion
  String searchQuery = encodeSpecial(Uri.encodeFull(uri).toString());
```

2021-11-28 04:35 UTC, jja08111 commented on lib/models/song.dart
> +String _bugsGetSongUrl(String title, String artist) {
함수 이름을 동사로 시작하는게 좋음 `getBugsSongUrl` 정도?

2021-12-01 00:20 UTC, jja08111 requested changes

2021-12-01 00:20 UTC, jja08111 commented on lib/constants/error_message.dart
> +const no_result = "NO RESULT";
`ageLimit`

2021-12-01 00:20 UTC, jja08111 commented on lib/constants/error_message.dart
> +}
이 클래스는 `bugs_lyrics_scraper.dart`으로 이동 ㄱㄱ
아래는 예제야
```dart
class AgeLimitException implements Exception {
  @override
  String toString() {
    return "🤔 노래 검색 에러\n성인인증이 필요한 곡입니다.";
  }
}

class SongNotFountException implements Exception {
  @override
  String toString() {
    return "🥲 해당 곡을 찾을 수 없습니다.";
  }
}

class LyricsNotFoundException implements Exception {
  final String _title;
  final String _artist;

  LyricsNotFoundException(this._title, this._artist);

  @override
  String toString() {
    return "😵 해당 곡의 가사를 찾을 수 없습니다.\n'Title: $_title\nArtist: $_artist'";
  }
}
```

2021-12-06 09:40 UTC, jja08111 commented on lib/constants/error_message.dart
> +}
아니면 Enum을 이용하여 기존에 너가 생성한 Exception을 수정해도 될 듯

2021-12-25 01:47 UTC, jja08111 requested changes

2021-12-25 01:47 UTC, jja08111 commented on lib/models/song.dart
> +  String? artist;
위에 3개의 변수를 `final String`으로 하는게 좋아보임 차후에 잘 못 수정하는 일이 없도록 하기 위해서(null일 수 없도록 ?를 빼는게 나아보임)

그러면 이 변수들이 `null`이 아니게 되는데 이 경우에는 생성자에서 `null`인 경우 공백('') 문자열로 넣어주면 될것같음

2021-12-25 01:47 UTC, jja08111 commented on lib/services/bugs_lyrics_scraper.dart
> +    if (elements.length == 0) return SongNotFoundException().toString();
throw가 아니라 return으로 했는데 맞는 것인가연?

2021-12-25 01:48 UTC, alpha-src commented on lib/services/bugs_lyrics_scraper.dart
> +    if (elements.length == 0) return SongNotFoundException().toString();
ㅎㄷ 저의 불찰입니다... 죄송해요 ㅠㅠ

2021-12-25 02:20 UTC, jja08111 commented on lib/models/song.dart
> +  String? artist;
```dart
Song.fromBugs(String title, String artist)
      : this.songURL = getBugsSongUrl(title, artist),
        this.artist = artist,
        this.title = title {
    this.lyrics = "";
}
```

2021-12-25 03:33 UTC, jja08111 approved these changes
![image](https://user-images.githubusercontent.com/57604817/147376788-8043f094-4ed4-434b-85be-92cac63c8cb2.png)

2021-12-25 03:34 UTC, merged